name: box_transform

packages:
  - packages/*
  - packages/**

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

ide:
  intellij: true

scripts:
  deps:
    run: |
      melos exec dart pub get
    description: Run `pub get` for all packages.
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  check-format:
    run: melos exec dart format --output none --set-exit-if-changed .
    description: Check formatting of Dart code.
  format:check:
    description: Check formatting of Dart code.
    run: dart format --output none --set-exit-if-changed .
  analyze:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos --fatal-warnings
  clean:
    run: melos exec flutter clean && melos exec dart pub get
  dry-run:
    run: melos exec flutter pub publish --dry-run
  build-web:
    run: cd packages/flutter_box_transform/example && flutter build web
  test:
    run: |
      cd packages/box_transform
      dart test .
    env:
      MELOS_TEST: true
  archive-web:
    run: |
      cd packages/flutter_box_transform/example
      flutter build web
      tar --directory build/web -cvf ../../../artifact.tar .
  lcov:
    run: |
      cd packages/box_transform
      dart pub run coverage:test_with_coverage
      dart pub run coverage:format_coverage --packages=.dart_tool/package_config.json --lcov -i coverage/coverage.json -o coverage/lcov.info
    env:
      MELOS_TEST: true
  cov:
    run: |
      cd packages/box_transform
      dart pub global run coverage:test_with_coverage
      dart pub global run coverage:format_coverage --packages=.dart_tool/package_config.json --lcov -i coverage/coverage.json -o coverage/lcov.info
      genhtml coverage/lcov.info -o coverage/html
    env:
      MELOS_TEST: true
  open_cov:
    run: open packages/box_transform/coverage/html/index.html