name: box_transform

packages:
  - packages/*
  - packages/**

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  deps:
    run: melos exec dart pub get
    description: Run `pub get` for all packages.
  analyze:
    exec: dart analyze .
  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.
  clean:
    run: melos exec flutter clean && melos exec dart pub get
  dry-run:
    run: melos exec flutter pub publish --dry-run
  build-web:
    run: cd packages/flutter_box_transform/example && flutter build web
  archive-web:
    run: |
      cd packages/flutter_box_transform/example
      flutter build web
      tar --directory build/web -cvf ../../../artifact.tar .