name: box_transform_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/box_transform
  - packages/flutter_box_transform
  - packages/flutter_box_transform/example
  - packages/flutter_box_transform/playground
