name: PR Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build example app
        working-directory: packages/flutter_box_transform/example
        run: flutter build web --release
