name: PR Code Quality

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output none --set-exit-if-changed .
      - name: Analyze
        run: dart analyze . --fatal-infos --fatal-warnings
      - name: Run box_transform tests
        working-directory: packages/box_transform
        run: flutter test
      - name: Run flutter_box_transform tests
        working-directory: packages/flutter_box_transform
        run: flutter test
