name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'

  workflow_dispatch:

jobs:
  tests_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: stable
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests with coverage
        working-directory: packages/box_transform
        run: |
          flutter pub run coverage:test_with_coverage
          flutter pub run coverage:format_coverage --packages=../../.dart_tool/package_config.json --lcov -i coverage/coverage.json -o coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/box_transform/coverage/lcov.info
          name: codecov-box-transform
